core.symlinks=false
core.autocrlf=true
core.fscache=true
color.diff=auto
color.status=auto
color.branch=auto
color.interactive=true
help.format=html
rebase.autosquash=true
http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
http.sslbackend=openssl
diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
credential.helper=manager
core.editor='D:\Software\Microsoft VS Code\Code.exe' --wait
user.name=johan@ryron.net
user.email=johan@ryron.net
url.https://${username}:${access_token}@github.com.insteadof=/https://github.com
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.ignorecase=true
remote.home.url=http://srv.mingsai.net:3000/volts-dev/orm
remote.home.fetch=+refs/heads/*:refs/remotes/home/*
remote.home.pushurl=http://srv.mingsai.net:3000/volts-dev/orm
user.name=HZMSRV
user.email=Johan@ryron.net
branch.master.remote=github
branch.master.merge=refs/heads/master
remote.github.url=https://github.com/volts-dev/orm
remote.github.fetch=+refs/heads/*:refs/remotes/github/*
